apiVersion: v1
kind: Pod
metadata:
  name: unixhat.com
  labels:
    app: nodejs
spec:
  containers:
  - name: k8s-nodejs
    image: heriyanto/k8s
    ports:
    - name: nodejs-port
      containerPort: 3000
